version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fialka
      POSTGRES_DB: Vacancies
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  main:
    build: ./Main
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:fialka@db:5432/Vacancies
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network

  service:
    build: ./Service
    command: flask run --host=0.0.0.0 --port=8000
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:fialka@db:5432/Vacancies
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:


networks:
  app-network:
    driver: bridge
